Tree.Minimise and Tree.ExtractMinimalLengthPathTree added
YaccConstructor/YaccConstructor pull request #216
Opened 2017-02-16 19:28 UTC by KochetovKirill

2017-02-16 19:35 UTC, gsvgit requested changes
Не нравятся мне эти ```do()```.

2017-02-16 19:35 UTC, gsvgit commented on src/AST.Common/ASTGLL.fs
> +                                    else do()
А здесь откуда ```do()``` ?
Что-то тут не так.

2017-02-16 20:05 UTC, KochetovKirill commented
Больше do() нет

2017-02-17 07:49 UTC, gsvgit requested changes

2017-02-17 07:49 UTC, gsvgit commented on src/AST.Common/ASTGLL.fs
> +                        if fst errer
А зачем короткие выражения на новые строчки переносить?

Вообще, мне сильно кажется, что конвертация переусложнена. Мне всё ещё кажется, что можно обойтись без дополнительных промежуточных типов.

2017-02-17 07:49 UTC, gsvgit commented on src/AST.Common/ASTGLL.fs
> +                            let l = f node.Left
Зачем так длинно?

2017-02-17 07:49 UTC, gsvgit commented on src/AST.Common/ASTGLL.fs
> +                                            match cu with Suc(x) -> nd <- x
А что будет, если там не Suc, а другие два варианта?

2017-02-17 07:49 UTC, gsvgit commented on src/AST.Common/ASTGLL.fs
> +                                | :? PackedNode as pckd ->
А что будет, если здесь не запакованная нода?

2017-02-17 21:14 UTC, MallabaevAzamat commented
TODO: refactoring (make ASTGLL more usable and readable)
comment for issue #199 
on current pr created many private types. Needs unify and open types and methods

2017-03-02 05:49 UTC, gsvgit commented
Решение мне не нравится, потому просто закрываю PR

2017-03-02 05:49 UTC, closed without merging