Parser input graph editing
YaccConstructor/YaccConstructor pull request #228
Opened 2017-03-22 11:33 UTC by likeanowl

Вернул две базовых реализации графов в AbstractAnalysis.Common;
Добавил возможность для API генерировать по грамматике, заданной строкой (надо обсудить)

2017-03-23 15:21 UTC, gsvgit requested changes

2017-03-23 15:21 UTC, gsvgit commented on src/AbstractAnalysis.Common/Graph.fs
> +    let StringToToken str = str |> int
magic!!!

2017-03-23 15:21 UTC, gsvgit commented on src/AbstractAnalysis.Common/Graph.fs
> +type ParserInputGraph<'EdgeObject>(initialVertices : int[], finalVertices : int[], ?edgeObjToString: ('EdgeObject -> string)) =
Seems that ```edgeObjToString``` should be to 'token or to int

2017-03-23 15:21 UTC, gsvgit commented on src/YaccConstructor/API.fs
> +let genStr grammar frontendName generatorName generatorParams conversions userDefs generateToFile =
Копипаста?

2017-03-23 15:21 UTC, gsvgit commented on src/YaccConstructor/API.fs
> +        run grammarFile true frontendName generatorName generatorParams conversions userDefs generateToFile
Ну аот не надо этих флажков.

2017-03-28 20:28 UTC, likeanowl commented
Разобью на две ветки и сделаю разные пуллреквесты для API и для реализации графа

2017-03-28 20:28 UTC, closed without merging