Parser Input Graph refactoring
YaccConstructor/YaccConstructor pull request #231
Opened 2017-03-29 09:40 UTC by likeanowl

Добавил в ParserInputGraph функцию tag -> int
Реализовал интерфейс IParserInput
Поправил существующий код, использующий ParserInputGraph.

2017-03-29 17:58 UTC, gsvgit requested changes

2017-03-29 17:58 UTC, gsvgit commented on src/AbstractAnalysis.Common/Graph.fs
> +
Кажется, потерян атрибут, управляюзий inline-ом

2017-03-29 17:58 UTC, gsvgit commented on src/AbstractAnalysis.Common/Graph.fs
>      inherit AdjacencyGraph<int, TaggedEdge<int, 'tagType>>()
А зачем два каласса: SimpleGraphInput и ParserInputGraph ? Они же об одном и том же.

2017-03-29 18:51 UTC, likeanowl commented on src/AbstractAnalysis.Common/Graph.fs
>      inherit AdjacencyGraph<int, TaggedEdge<int, 'tagType>>()
Ну, их изначально было 2, я решил оставить.

2017-03-29 19:10 UTC, likeanowl commented on src/AbstractAnalysis.Common/Graph.fs
>      inherit AdjacencyGraph<int, TaggedEdge<int, 'tagType>>()
А, ну теперь SimpleGraphInput можно выпилить, в принципе

2017-03-29 19:12 UTC, gsvgit commented
Только то, что останется лучше назвать как раз SimpleGraphInput.
ParserInputGraph -- какое-то древнее мифическое существо и от него как-то
хочется избавиться.

Regards,
Semyon Grigorev.

2017-03-29 22:10 GMT+03:00 Sergey Svitkov <notifications@github.com>:

> *@likeanowl* commented on this pull request.
> ------------------------------
>
> In src/AbstractAnalysis.Common/Graph.fs
> <https://github.com/YaccConstructor/YaccConstructor/pull/231#discussion_r108761975>
> :
>
> > @@ -73,6 +95,7 @@ type SimpleGraphInput<'tagType> (initialPositions, getTokenFromTag:'tagType -> i
>      inherit AdjacencyGraph<int, TaggedEdge<int, 'tagType>>()
>
> А, ну теперь SimpleGraphInput можно выпилить, в принципе
>
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub
> <https://github.com/YaccConstructor/YaccConstructor/pull/231#discussion_r108761975>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAGhQEu4AyEhVL6N7a4oVJKsapGU47mkks5rqqymgaJpZM4MsvOq>
> .
>

2017-03-29 20:26 UTC, likeanowl commented
Поправил

2017-03-30 08:18 UTC, gsvgit approved these changes

2017-03-30 08:18 UTC, merged

2017-03-30 08:19 UTC, gsvgit commented
Принято.

Regards,
Semyon Grigorev.

2017-03-29 23:26 GMT+03:00 Sergey Svitkov <notifications@github.com>:

> Поправил
>
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub
> <https://github.com/YaccConstructor/YaccConstructor/pull/231#issuecomment-290215206>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAGhQA_Fu5o9e_YwDytIKi6zjQI84Qj7ks5rqr6KgaJpZM4MsvOq>
> .
>