Now we have sppf to path set conversion (probably)
YaccConstructor/YaccConstructor pull request #245
Opened 2017-05-11 19:42 UTC by likeanowl

Если я всё правильно понял, то теперь можно вытащить из SPPF все терминальные ноды и получить тройки в духе (token, startVertice, endVertice).

2017-05-11 20:14 UTC, gsvgit requested changes

2017-05-11 20:14 UTC, gsvgit commented on src/GLLAbstractParser/SPPF.fs
> +let GetPathSet (sppf : SPPF) =
Path ? Кажется, до путей тут ещё далеко. Просто токены с позициями

2017-05-11 20:14 UTC, gsvgit commented on src/AST.Common/ASTGLLFSA.fs
> +    member this.getRightExtension = int <| ((int64 this.Extension) &&& 0xffffffffL)
Мне кажется, что где-то уже есть эти функции. понятно, что они простые, но лучше использовать одну, дабы не страдать, если поменяется формат сжатия. посмотрите, где создаются узлы, какие функции там применяются для упаковки. Где-то рядом должна быть распаковка.

2017-05-11 20:16 UTC, likeanowl commented on src/GLLAbstractParser/SPPF.fs
> +let GetPathSet (sppf : SPPF) =
Ну, это же легко преобразуется в ребра с метками.

2017-05-11 20:20 UTC, likeanowl commented on src/GLLAbstractParser/SPPF.fs
> +let GetPathSet (sppf : SPPF) =
Ну, понятно, что уже на стороне моей библиотеки

2017-05-11 20:21 UTC, gsvgit commented on src/GLLAbstractParser/SPPF.fs
> +let GetPathSet (sppf : SPPF) =
Вот да. А здесь такое название не кажется уместным. Опять же, SPPF не обязан быть связан с графом. Так что какие тут пути?

2017-05-11 20:25 UTC, likeanowl commented on src/GLLAbstractParser/SPPF.fs
> +let GetPathSet (sppf : SPPF) =
Хорошо, сейчас переименую.

2017-05-11 21:24 UTC, likeanowl commented on src/AST.Common/ASTGLLFSA.fs
> +    member this.getRightExtension = int <| ((int64 this.Extension) &&& 0xffffffffL)
обновил

2017-05-12 05:04 UTC, gsvgit approved these changes

2017-05-12 05:04 UTC, merged