Removed addins
YaccConstructor/YaccConstructor pull request #246
Opened 2017-05-12 01:33 UTC by likeanowl

Удалил аддины, всё собралось и даже тесты прошли.
Issue #242 solved?

![proof](https://cloud.githubusercontent.com/assets/10586429/25978621/044aaf66-36cc-11e7-9671-ee5021766fe4.png)

2017-05-12 01:49 UTC, likeanowl commented
Не понял, почему не собирается. Попробую сейчас руками всё почистить, т.к. как-то странно.
![untitled](https://cloud.githubusercontent.com/assets/10586429/25978943/30a15810-36ce-11e7-9ccc-d5278dee1a5a.png)

2017-05-12 07:28 UTC, gsvgit requested changes
Ещё я не заметил, чтобы из конфигов пакета исчезли Mono.Addins. Это очень странно. Вы случайно не просто руками удалили ссылку на либу? Надо не забыть снести пакет.

2017-05-12 07:28 UTC, gsvgit commented on src/Common/Conversion.fs
> +
```do()``` тоже нужно удалять. Эта конструкция только для того нужна, чтобы быдл к чему аттрибут повесить.

2017-05-12 07:28 UTC, gsvgit commented on src/Common/Generator.fs
> +
Здесь тоже. Проверьте везде.

2017-05-12 07:28 UTC, gsvgit commented on src/Conversions/ToCNF.fs
> +
Лишние переносы строк тоже лучше удалять.

2017-05-12 07:28 UTC, gsvgit commented on src/YaccConstructor/Addin.fs
> +(*
Так от этого файла хоть что-то осталось? Может его весь удалить?

2017-05-12 23:32 UTC, likeanowl commented
Примерный список gen.cmd, которые нужно переписать на .fsx скрипты.
[change.txt](https://github.com/YaccConstructor/YaccConstructor/files/998151/change.txt)

2017-05-24 01:44 UTC, likeanowl commented
Выпилил ~10 тестов, т.к. для них почему-то не генерились .yrd.fs файлы (ошибки в InitialConvert).
Сейчас всё собирается, но с тестами какие-то проблемы остались. 
Пока не коммитил.

2017-05-24 01:57 UTC, likeanowl commented
![untitled](https://cloud.githubusercontent.com/assets/10586429/26383780/7e57e1aa-403d-11e7-93a6-641e8088f1c9.png)
¯\_(ツ)_/¯

2017-05-24 02:15 UTC, likeanowl commented
Осталось только переписать в build.fsx и подчистить файлы с reference'ами.

2017-05-26 23:09 UTC, likeanowl commented
Ну, вроде собирается на appveyor'e, с трэвисом не знаю, что не так. Ну, точнее знаю -- судя по логу, там не поддерживается исполнение fsx с помощью FAKE (Ваш К.О.). Ок это или нет?

По поводу того, что осталось сделать -- подчистить файлы paket.

2017-05-26 23:52 UTC, likeanowl commented
Вроде всё почистил

2017-05-27 16:28 UTC, merged