BFS on SPPF, idk ok or not
YaccConstructor/YaccConstructor pull request #247
Opened 2017-05-21 18:31 UTC by likeanowl

2017-05-22 05:08 UTC, gsvgit requested changes

2017-05-22 05:08 UTC, gsvgit commented on src/GLLAbstractParser/SPPF.fs
> +            if (n.Equals(s)) then
Кажется, это просто  ```used.Add(n, n.Equals(s))```

2017-05-22 05:08 UTC, gsvgit commented on src/GLLAbstractParser/SPPF.fs
> +            while (queue.Count <> 0) do
Скобки вокруг условий в F# не нужны

2017-05-22 05:08 UTC, gsvgit commented on src/GLLAbstractParser/SPPF.fs
> +        let mutable used = new Dictionary<INode, bool>()
Мутабельный словарь!?

В любом случае, не надо лишние типы указывать.

2017-05-22 06:41 UTC, likeanowl commented on src/GLLAbstractParser/SPPF.fs
> +            if (n.Equals(s)) then
... действительно

2017-05-22 11:19 UTC, gsvgit requested changes

2017-05-22 11:19 UTC, gsvgit commented on src/GLLAbstractParser/SPPF.fs
> +                | _ -> do()
Точно? А что если у нас таки есть запакованные узлы (PackedNode)? Что-то тут не так.

2017-05-22 11:19 UTC, gsvgit commented on src/GLLAbstractParser/SPPF.fs
> +                | :? NonTerminalNode as n -> n.MapChildren (fun x -> if not used.[x] then
В F# then принято писать на новой строке.

2017-05-22 11:19 UTC, gsvgit commented on src/GLLAbstractParser/SPPF.fs
> +    member this.Iterate (s : NonTerminalNode) =
Что-то я не уверен, что эта функция что-то реально возвращает.  Единственный результат завёрнут в ignore.

2017-05-22 12:32 UTC, likeanowl commented
вроде теперь должно быть ок

2017-05-22 12:33 UTC, gsvgit requested changes

2017-05-22 12:33 UTC, gsvgit commented on src/GLLAbstractParser/SPPF.fs
> +                | :? NonTerminalNode as n -> n.MapChildren (fun x -> if not used.[x]
А iterChildren нету? У каких-то узлов вроде было.

2017-05-22 12:33 UTC, gsvgit commented on src/GLLAbstractParser/SPPF.fs
> +                                        then
Можно в одну строку
```
if cond
then eeee
else fffff
```

2017-05-22 12:33 UTC, gsvgit commented on src/GLLAbstractParser/SPPF.fs
>                  | _ -> do()
А я бы падал, чтобы было понятно, что в дереве вдруг какие-то странные узлы затесались. А то долго гадать будете, что именно не так.

2017-05-22 12:43 UTC, likeanowl commented on src/GLLAbstractParser/SPPF.fs
> +                | :? NonTerminalNode as n -> n.MapChildren (fun x -> if not used.[x]
неа, только map.

2017-05-22 13:16 UTC, gsvgit requested changes

2017-05-22 13:16 UTC, gsvgit commented on src/GLLAbstractParser/SPPF.fs
> +                | _ -> failwith "Strange type of node"
Заменить на что-то вроде 
```
|  x -> failwithf "Strange type of node: %A" x
```

Чтобы сразу знать, что там за странный тип.

2017-05-22 13:16 UTC, gsvgit commented on src/GLLAbstractParser/SPPF.fs
> +    member this.IterateFromAnyNonTerm (s : NonTerminalNode) =
Прям с конкретного узла? А если одному нетерминалу соответствует несколько узлов (а часто именно так и есть)?

2017-05-22 13:32 UTC, gsvgit requested changes

2017-05-22 13:32 UTC, gsvgit commented on src/GLLAbstractParser/SPPF.fs
> +    member this.Iterate (s : NonTerminalNode) =
К названию предыдущий комментарий не имеет отношения. Мне впринципе интересна сигнатура. Как Вы изначально будете искать все эти узлы? Вот хочу я все пути из нетерминала "nterm125", который совсем не обязан быть стартовым. Значит нужна ещё одна функция, которая в SPPF будет искать нужные узлы, с которых нужно начинать обход.

2017-05-22 13:49 UTC, likeanowl commented
написал поиск по инту, т.к. достать string -> int можно только из ParserSource (?).

2017-05-23 06:23 UTC, gsvgit commented
Да, скорее всего только оттуда.

Пусть пока так.

2017-05-23 06:23 UTC, gsvgit approved these changes

2017-05-23 06:23 UTC, merged