Made iterator param maxLength optional
YaccConstructor/YaccConstructor pull request #264
Opened 2017-08-21 21:57 UTC by likeanowl

2017-09-04 07:22 UTC, gsvgit requested changes

2017-09-04 07:22 UTC, gsvgit commented on src/GLLAbstractParser/SPPF.fs
> +        let unwrapped = match maxLength with
В F# есть опцианальные параметры: https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/parameters-and-arguments#optional-parameters   Кажется, здесь они будут уместны.

2017-09-04 07:41 UTC, gsvgit requested changes

2017-09-04 07:41 UTC, gsvgit commented on src/GLLAbstractParser/SPPF.fs
> +            while queue.Count > 0 && (unwrapped = -1 || length.Value < unwrapped) do
```length.Value``` <-> ```!length```

2017-09-04 07:41 UTC, gsvgit commented on src/GLLAbstractParser/SPPF.fs
>          Seq.iter (fun x -> queue.Enqueue x) s
```
Seq.iter (fun x -> queue.Enqueue x) s
```
<->
```
Seq.iter queue.Enqueue s
```

2017-09-04 07:41 UTC, gsvgit commented on src/GLLAbstractParser/SPPF.fs
>          Seq.iter (fun x -> queue.Enqueue x) s
И то же самое в других места.

2017-09-04 23:49 UTC, likeanowl commented
Что не так с тестами? ¯\\_(ツ)_/¯

2017-09-05 09:20 UTC, gsvgit commented
Что б я знал...

Regards,
Semyon Grigorev.

2017-09-05 2:49 GMT+03:00 Sergey Svitkov <notifications@github.com>:

> Что не так с тестами? ¯\*(ツ)*/¯
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/YaccConstructor/YaccConstructor/pull/264#issuecomment-327040135>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAGhQN9G6eImjhCZuLBnCSfFKJe66Nivks5sfIx5gaJpZM4O93_K>
> .
>

2017-11-11 15:53 UTC, closed without merging