compression frontend
YaccConstructor/YaccConstructor pull request #282
Opened 2017-10-05 23:22 UTC by ZinovyevaAnna

2017-10-06 05:37 UTC, gsvgit requested changes
Замечания в комментариях.
И unit-тесты добавьте, пожалуйста.

2017-10-06 05:37 UTC, gsvgit commented on src/CompressionFrontend/Compression.fs
> +                            if x.isNonTerminal()
Чтобы не расползалось по высоте, такие вещи можно форматировать так:
```
if x.isNonTerminal() 
then PRef(Source.t ("sq_" + (x.Value).ToString()), None)
else  PToken(Source.t ((char(x.Value)).ToString()))
```

2017-10-06 05:37 UTC, gsvgit commented on src/CompressionFrontend/Compression.fs
> +        if s = null || s.Next = null || s.Value.Value = special || s.Next.Value.Value = special
А Вы можете рассказать, что должен делать этот код? Такое ощущение, что можно существенно короче записать. В любом случае, ```if cond then false``` -- это зло.

2017-10-06 05:37 UTC, gsvgit commented on src/CompressionFrontend/Compression.fs
> +    let numTerminals = 100000
А что это за магическая константа?

2017-10-06 05:37 UTC, gsvgit commented on src/CompressionFrontend/Compression.fs
> +        if s.Value.isNonTerminal()
Такие вещи, впринципе, тоже можно в 2 строки писать:
```
if s.Value.isNonTerminal()
then s.Value.Rule.DecCount()
```

2017-10-06 10:30 UTC, ZinovyevaAnna commented on src/CompressionFrontend/Compression.fs
> +        if s = null || s.Next = null || s.Value.Value = special || s.Next.Value.Value = special
Здесь мы проверяем, что то, что получила функция, точно диграм, и что он не содержит специального символа. Можно проверять это перед вызовом функции check, но тогда эта же строчка будет вместо одного раза несколько

2017-10-06 10:35 UTC, ZinovyevaAnna commented on src/CompressionFrontend/Compression.fs
> +    let numTerminals = 100000
Для того, чтобы сравнивать два символа и не проверять каждый раз одного ли они типа, и терминалы, и нетерминалы имеют числовое значение. Ну и чтобы у них были разные значения, нетерминалы начинаются только с номера numTerminals

2017-10-07 07:17 UTC, gsvgit requested changes
Я всё ещё не могу разобраться в этом огромном if-е, но мне кажется, что он какой-то странный. Объясните, пожалуйста, что в нём происходит.

2017-10-07 07:17 UTC, gsvgit commented on src/CompressionFrontend/Compression.fs
> +        if s = null || s.Next = null || s.Value.Value = special || s.Next.Value.Value = special
Это Вы про конкретно это условие. А весь этот огромный if что делает?

2017-10-07 09:46 UTC, ZinovyevaAnna commented on src/CompressionFrontend/Compression.fs
> +        if s = null || s.Next = null || s.Value.Value = special || s.Next.Value.Value = special
Если в целом, то он идет по всем правилам, и ищет, нет ли такого же диграма в них. А если про то, почему он так странно выглядит, то это я просто не смогла придумать ничего умнее, чем две рекурсивные функции для этого. В одной мы идем по правилам, а в другой по символам в правиле. Хотя конечно это можно сделать с помощью двух while. Переделать на while?

2017-10-09 06:31 UTC, gsvgit commented on src/CompressionFrontend/Compression.fs
> +        if s = null || s.Next = null || s.Value.Value = special || s.Next.Value.Value = special
Не, на while не надо. Мне кажется, что тут каким-нибудь аккуратным fold-ом можно обойтись. Страно, что по ходу дела, вместе с проверкой ещё что-то вызывается. Казалось бы, должна быть булева функция без побочных эффектов.

2017-10-09 07:18 UTC, ZinovyevaAnna commented on src/CompressionFrontend/Compression.fs
> +        if s = null || s.Next = null || s.Value.Value = special || s.Next.Value.Value = special
Как раз таки как только мы находим этот диграм, мы его обрабатываем, а потом возвращаем bool. Точнее, эта функция возвращает не то, нашли ли мы диграм, а подчинили ли мы его какому нибудь правилу или нет.

2017-10-12 06:03 UTC, gsvgit commented on src/CompressionFrontend/Compression.fs
> +                if Rules.ContainsKey(i) && nextSym (Rules.Item(i)).lst.First i
```
Rules.ContainsKey(i) && nextSym (Rules.Item(i)).lst.First i
|(i < numRules && nextRule (i + 1))
```

2017-10-12 06:03 UTC, gsvgit approved these changes

2017-10-12 06:03 UTC, merged